import * as functions from 'firebase-functions';
import {fulldatabaseHandler} from './fulldatabaseHandler';
import {feedbackHandler} from './feedbackHandler';
import {uniqueIdApp} from './uniqueidHandler';
import {searchHandler} from './searchHandler';
import generateLowerCaseNamesHandler from './generateLowerCaseNames';
import {indexTitlesHandler} from './indexTitles';
import categoryKeysHandler from './categoryKeys';
import {resOnCreate, resOnDelete, resOnUpdate} from './dbtrigger/resTriggerFunctions';
import {catOnCreate, catOnDelete, catOnUpdate} from './dbtrigger/catTriggerFunctions';

export const fulldatabase = functions.https.onRequest(fulldatabaseHandler);
export const feedback = functions.https.onRequest(feedbackHandler);
export const uniqueid = functions.https.onRequest(uniqueIdApp);
export const search = functions.https.onRequest(searchHandler);
export const generateLowerCaseNames = functions.https.onRequest(generateLowerCaseNamesHandler);
// export const resourcesOnCreate = onCreateHandlerFactory('resources');
export const resourcesOnCreate = resOnCreate;
export const resourcesOnDelete = resOnDelete;
export const resourcesOnUpdate = resOnUpdate;
export const categoriesOnCreate = catOnCreate;
export const categoriesOnUpdate = catOnUpdate;
export const categoriesOnDelete = catOnDelete;
export const titleindex = functions.https.onRequest(indexTitlesHandler);
export const categoryKeys = functions.https.onRequest(categoryKeysHandler);
